# filename: autentik-minimal-secrets.yaml
# description: Minimal Authentik configuration using secrets from an existing Kubernetes Secret
# install: helm upgrade --install authentik authentik/authentik -f provision-host/kubernetes/12-auth/not-in-use/autentik-minimal-secrets.yaml -n authentik --create-namespace
# uninstall: helm uninstall authentik -n authentik

authentik:
  error_reporting:
    enabled: true

  # PostgreSQL connection (password from AUTHENTIK_POSTGRESQL__PASSWORD in secret)
  postgresql:
    host: "postgresql.default.svc.cluster.local"
    name: authentik
    user: authentik
    port: 5432

  # Redis connection (password from AUTHENTIK_REDIS__PASSWORD in secret)
  redis:
    host: "redis-master.default.svc.cluster.local"
    port: 6379

global:
  # Load all required environment variables from the urbalurba-secrets secret
  envFromSecrets:
    - urbalurba-secrets

server:
  ingress:
    ingressClassName: traefik
    enabled: true
    hosts:
      - authentik.localhost

# Disable built-in PostgreSQL and Redis because we're using external ones
postgresql:
  enabled: false
redis:
  enabled: false