apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apache-spark
  description: "Kubernetes-native distributed data processing engine"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/analytics/spark
    backstage.io/kubernetes-id: apache-spark
    backstage.io/kubernetes-namespace: default
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/analytics/spark"
    uis.sovereignsky.no/business-owner: "business-owners"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/analytics/spark
      title: "apache-spark Docs"
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: app-team
  system: analytics
