apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd
  description: "GitOps continuous delivery - automates deployments from Git repositories"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/management/argocd
    backstage.io/kubernetes-id: argocd
    backstage.io/kubernetes-namespace: argocd
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/management/argocd"
    uis.sovereignsky.no/business-owner: "business-owners"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/management/argocd
      title: "argocd Docs"
      icon: docs
spec:
  type: tool
  lifecycle: production
  owner: platform-team
  system: management
