apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jupyterhub
  description: "Multi-user Jupyter notebooks with PySpark pre-configured"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/analytics/jupyterhub
    backstage.io/kubernetes-id: jupyterhub
    backstage.io/kubernetes-namespace: jupyterhub
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/analytics/jupyterhub"
    uis.sovereignsky.no/business-owner: "business-owners"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/analytics/jupyterhub
      title: "jupyterhub Docs"
      icon: docs
spec:
  type: tool
  lifecycle: production
  owner: app-team
  system: analytics
