apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openmetadata
  description: "Data discovery, governance, and metadata platform"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/analytics/openmetadata
    backstage.io/kubernetes-id: openmetadata
    backstage.io/kubernetes-namespace: openmetadata
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/analytics/openmetadata"
    uis.sovereignsky.no/business-owner: "business-owners"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/analytics/openmetadata
      title: "openmetadata Docs"
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: app-team
  system: analytics
  dependsOn:
    - resource:postgresql
    - resource:elasticsearch
