apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openwebui
  description: "ChatGPT-like web interface for AI models, routes requests via LiteLLM"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/ai/openwebui
    backstage.io/kubernetes-id: openwebui
    backstage.io/kubernetes-namespace: ai
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/ai/openwebui"
    uis.sovereignsky.no/business-owner: "business-owners"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/ai/openwebui
      title: "openwebui Docs"
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: app-team
  system: ai
  dependsOn:
    - resource:postgresql
    - component:litellm
