apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sovdev-logger
  description: "Multi-language OTLP integration library for sending telemetry from applications"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/observability/sovdev-logger
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/observability/sovdev-logger"
    uis.sovereignsky.no/business-owner: "business-owners"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/observability/sovdev-logger
      title: "sovdev-logger Docs"
      icon: docs
spec:
  type: library
  lifecycle: production
  owner: platform-team
  system: observability
  dependsOn:
    - component:otlp-collector
