apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: applications
  description: "Applications system within the UIS platform"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/applications
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/applications"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/applications
      title: "Applications Docs"
      icon: docs
spec:
  owner: app-team
  domain: uis-infrastructure
