apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: identity
  description: "Identity system within the UIS platform"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/identity
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/identity"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/identity
      title: "Identity Docs"
      icon: docs
spec:
  owner: platform-team
  domain: uis-infrastructure
