apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: management
  description: "Management system within the UIS platform"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/management
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/management"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/management
      title: "Management Docs"
      icon: docs
spec:
  owner: platform-team
  domain: uis-infrastructure
