apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: observability
  description: "Observability system within the UIS platform"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/observability
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/observability"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/observability
      title: "Observability Docs"
      icon: docs
spec:
  owner: platform-team
  domain: uis-infrastructure
