# File: 073-traefik-forward-auth-middleware.yaml
#
# Description:
# Traefik Middleware configuration to enable forward authentication for applications.
# - Delegates authentication checks to the Authentik outpost service.
# - Defines which HTTP headers to expect and pass to downstream applications.
#
# Requirements:
# - The Authentik outpost service must be running in the cluster.
# - The Traefik Kubernetes IngressRoute provider must be enabled.
#
# Usage:
# apply to cluster: kubectl apply -f manifests/073-traefik-forward-auth-middleware.yaml
#
# Debugging commands:
# check resource: kubectl get middleware authentik-forwardauth -n default
# view logs of Traefik pod: kubectl logs -l app.kubernetes.io/name=traefik -n traefik
#
# Notes:
# - The `address` must point to the internal ClusterIP service of the Authentik outpost.
# - The `@kubernetescrd` suffix is used to reference this middleware in an IngressRoute.
# - This middleware is a reusable component for all applications requiring authentication.
#
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authentik-forwardauth
  namespace: default
spec:
  forwardAuth:
    # CRITICAL: Use the actual outpost service name and port
    address: http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/traefik
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User
      - X-Forwarded-Email
      - X-Forwarded-Groups
      - X-Forwarded-Preferred-Username