# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# 076-authentik-simple-whoami-blueprint.yaml
# 
# Description:
# Minimal Authentik blueprint that creates ONLY a basic whoami application
# - Simple application entry (no complex flows or providers)
# - Tests basic blueprint functionality
#
# Usage:
#   kubectl apply -f 076-authentik-simple-whoami-blueprint.yaml
#
# Prerequisites:
# - Authentik deployed with Helm chart
# - Helm values must include: authentik.blueprints.configMaps: [authentik-combined-blueprints]

apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-combined-blueprints
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: blueprint
    blueprints.goauthentik.io/instantiate: "true"
data:
  whoami-simple.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
      name: "Simple Whoami App"
      labels:
        blueprints.goauthentik.io/instantiate: "true"
        blueprints.goauthentik.io/description: "Minimal blueprint to create whoami app"
    
    context: {}
    
    entries:
      # Create a simple application (no provider, just the app)
      - model: authentik_core.application
        state: present
        identifiers:
          slug: "whoami"
        attrs:
          name: "Whoami Test App"
          slug: "whoami"
          meta_launch_url: "http://whoami.localhost"
          policy_engine_mode: "any"
