# File: manifests/078-whoami-protected-ingressroute.yaml
#
# Description:
# IngressRoute for whoami service with Authentik forward authentication middleware
# Routes both internal (.localhost) and external (.urbalurba.no) domains through authentication
# Provides protected access to the same service available publicly at whoami-public.localhost
# Automatically handles both development and demo mode access via HostRegexp routing
#
# HostRegexp Routing:
# This IngressRoute uses HostRegexp('whoami\..+') to automatically handle:
# - whoami.localhost (internal development access with authentication)
# - whoami.urbalurba.no (external demo access with authentication via Cloudflare tunnel)
# - Any future domains (future-proof routing)
#
# Authentication Flow:
# - Unauthenticated users are redirected to Authentik login page
# - After successful authentication, users are redirected back to the whoami service
# - The service receives authentication headers for user identification
#
# Usage:
# kubectl apply -f 078-whoami-protected-ingressroute.yaml
#
# Dependencies:
# - 070-whoami-service-and-deployment.yaml (whoami service must exist)
# - 075-authentik-config.yaml (Authentik must be deployed and running)
# - 077-authentik-forward-auth-middleware.yaml (middleware must be defined)
# - Authentik UI configuration must be completed (see UI Configuration section)
#
# UI Configuration Prerequisites:
# Before deploying this file, complete these steps in Authentik UI (https://authentik.urbalurba.no):
# 1. Create Application: name="whoami", slug="whoami"
# 2. Create Proxy Provider: name="whoami-provider", mode="Forward auth (single application)", external_host="https://whoami.urbalurba.no"
# 3. Link Provider to Application: edit whoami application, assign whoami-provider
# 4. Configure Outpost: edit "authentik Embedded Outpost", add whoami application
#
# Testing:
# Internal (Development):
# - Unauthenticated: curl -L http://whoami.localhost
# - Should redirect to Authentik login page
# - Authenticated (browser): open http://whoami.localhost
# - Should redirect to login, then return to whoami with authentication headers
#
# External (Demo):
# - Unauthenticated: curl -L https://whoami.urbalurba.no
# - Should redirect to Authentik login page
# - Authenticated (browser): open https://whoami.urbalurba.no
# - Should redirect to login, then return to whoami with authentication headers
#
# Compare with public route: curl http://whoami-public.localhost
# Should show same service without authentication requirements
#
# Authentication Headers:
# When properly configured, the following headers are passed to whoami:
# - X-Forwarded-User
# - X-Forwarded-Email
# - X-Forwarded-Groups
# - X-Forwarded-Name
# - X-Forwarded-Preferred-Username
# - X-Forwarded-User-Id
#
# Cluster Standards Compliance:
# - Uses traefik.io/v1alpha1 API version
# - IngressRoute CRD (follows cluster ingress standards)
# - References middleware by name and namespace
# - Implements HostRegexp pattern for unified routing
#
# Authentik 2025.8 Compatibility:
# - Forward authentication flow unchanged
# - Middleware integration unchanged
# - Authentication headers unchanged
#
# HostRegexp Pattern Explanation:
# - 'whoami\..+' matches any domain that starts with 'whoami.'
# - Examples: whoami.localhost, whoami.urbalurba.no, whoami.example.com
# - The '\.' escapes the literal dot, '+' matches one or more characters
# - This enables automatic external access without duplicating IngressRoute rules
# - Note: This rule applies to the protected whoami service (not whoami-public)

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-protected
  namespace: default
  labels:
    app: whoami
    type: protected
    routing: unified
    protection: authentik-forward-auth
spec:
  entryPoints:
    - web
  routes:
    - match: HostRegexp(`whoami\..+`)
      kind: Rule
      services:
        - name: whoami
          port: 80
      middlewares:
        - name: authentik-forward-auth
          namespace: default