# 230-promstack/config.yaml
# 
# Description:
# Configuration for Promstack Helm chart deployment
# This sets up a full statefulset promstack with Prometheus, Grafana, Alertmanager, and Node Exporter with micro-k8s as storage class
# Ingress is enabled for Prometheus, Grafana, and Alertmanager using Traefik reachable at *.localhost
#
# Usage:
# installing: helm install prometheus-stack prometheus-community/kube-prometheus-stack -n monitoring --create-namespace -f 230-promstack-config.yaml --version 45.7.1
# upgrading:  helm upgrade prometheus-stack prometheus-community/kube-prometheus-stack -n monitoring --create-namespace --install -f 230-promstack-config --version 45.7.1
# uninstalling: helm uninstall prometheus-stack -n monitoring

prometheusOperator:
  image:
    registry: quay.io
    repository: prometheus-operator/prometheus-operator
    tag: v0.65.1
  prometheusConfigReloader:
    image:
      registry: quay.io
      repository: prometheus-operator/prometheus-config-reloader
      tag: v0.65.1

prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.localhost
    paths:
      - /
    pathType: Prefix
  prometheusSpec:
    image:
      registry: quay.io
      repository: prometheus/prometheus
      tag: v2.44.0
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: microk8s-hostpath
          resources:
            requests:
              storage: 5Gi
    retention: 30d

grafana:
  image:
    registry: docker.io
    repository: grafana/grafana
    tag: 9.5.2
  persistence:
    enabled: true
    storageClassName: microk8s-hostpath
    size: 2Gi
  adminUser: admin
  adminPassword: admin123

  # Enable and configure ingress
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.localhost
    paths:
      - path: /
        pathType: Prefix

  # Configure Grafana for sub-path
  grafana.ini:
    server:
      domain: grafana.localhost
      root_url: "http://grafana.localhost"
      serve_from_sub_path: true
    auth:
      disable_login_form: false
      disable_signout_menu: false

nodeExporter:
  image:
    registry: quay.io
    repository: prometheus/node-exporter
    tag: v1.5.0
  serviceMonitor:
    relabelings:
      - sourceLabels: [__meta_kubernetes_endpoint_node_name]
        targetLabel: nodename

alertmanager:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - alertmanager.localhost
    paths:
      - /
    pathType: Prefix
  alertmanagerSpec:
    image:
      registry: quay.io
      repository: prometheus/alertmanager
      tag: v0.25.0
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: microk8s-hostpath
          resources:
            requests:
              storage: 1Gi
