apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: developer1
  description: "UIS team member"
spec:
  profile:
    displayName: "App Developer"
    email: "developer@sovereignsky.no"
  memberOf:
    - app-team
