apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qdrant
  description: "Vector search database, available for user workloads"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/databases/qdrant
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/databases/qdrant"
    uis.sovereignsky.no/business-owner: "business-owners"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/databases/qdrant
      title: "qdrant Docs"
      icon: docs
spec:
  type: database
  owner: platform-team
  system: databases
