apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloudflare-tunnel
  description: "Secure tunnel to expose UIS services via Cloudflare's network with custom domains"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/networking/cloudflare-tunnel
    backstage.io/kubernetes-id: cloudflare-tunnel
    backstage.io/kubernetes-namespace: default
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/networking/cloudflare-tunnel"
    uis.sovereignsky.no/business-owner: "business-owners"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/networking/cloudflare-tunnel
      title: "cloudflare-tunnel Docs"
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: networking
