apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana
  description: "Visualization dashboards for all observability data - queries Prometheus, Loki and Tempo"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/observability/grafana
    backstage.io/kubernetes-id: grafana
    backstage.io/kubernetes-namespace: monitoring
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/observability/grafana"
    uis.sovereignsky.no/business-owner: "business-owners"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/observability/grafana
      title: "grafana Docs"
      icon: docs
spec:
  type: tool
  lifecycle: production
  owner: platform-team
  system: observability
  dependsOn:
    - component:prometheus
    - component:loki
    - component:tempo
