apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: loki
  description: "Log aggregation with label-based indexing"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/observability/loki
    backstage.io/kubernetes-id: loki
    backstage.io/kubernetes-namespace: monitoring
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/observability/loki"
    uis.sovereignsky.no/business-owner: "business-owners"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/observability/loki
      title: "loki Docs"
      icon: docs
spec:
  type: tool
  lifecycle: production
  owner: platform-team
  system: observability
