apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pgadmin
  description: "Web-based administration UI for PostgreSQL"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/management/pgadmin
    backstage.io/kubernetes-id: pgadmin
    backstage.io/kubernetes-namespace: default
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/management/pgadmin"
    uis.sovereignsky.no/business-owner: "business-owners"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/management/pgadmin
      title: "pgadmin Docs"
      icon: docs
spec:
  type: tool
  lifecycle: production
  owner: platform-team
  system: management
  dependsOn:
    - resource:postgresql
