apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prometheus
  description: "Metrics collection and storage for all UIS services"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/observability/prometheus
    backstage.io/kubernetes-id: prometheus
    backstage.io/kubernetes-namespace: monitoring
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/observability/prometheus"
    uis.sovereignsky.no/business-owner: "business-owners"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/observability/prometheus
      title: "prometheus Docs"
      icon: docs
spec:
  type: tool
  lifecycle: production
  owner: platform-team
  system: observability
