apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: app-team
  description: "Application team responsible for AI, integration, analytics and applications"
  annotations:
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs"
spec:
  type: team
  children: []
  members:
    - developer1
