apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: "Platform engineering team responsible for infrastructure, observability, identity, networking and management"
  annotations:
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs"
spec:
  type: team
  children: []
  members:
    - terje
