apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: analytics
  description: "Analytics system within the UIS platform"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/analytics
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/analytics"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/analytics
      title: "Analytics Docs"
      icon: docs
spec:
  owner: app-team
  domain: uis-infrastructure
