apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: databases
  description: "Databases system within the UIS platform"
  annotations:
    backstage.io/techdocs-ref: url:https://uis.sovereignsky.no/docs/packages/databases
    uis.sovereignsky.no/docs-url: "https://uis.sovereignsky.no/docs/packages/databases"
  links:
    - url: https://uis.sovereignsky.no/docs/packages/databases
      title: "Databases Docs"
      icon: docs
spec:
  owner: platform-team
  domain: uis-infrastructure
