#!/bin/bash
# File: platforms/aks/scripts/01-apply.sh
#
# Description:
#   Runs OpenTofu init → plan → apply for the AKS platform.
#   Reads all values from azure-aks-config.sh — no manual tfvars editing needed.
#   Writes kubeconfig output to the standard UIS kubeconfig location.
#
# Prerequisites:
#   - Running inside provision-host container
#   - azure-aks-config.sh exists (copied from template and filled in)
#   - scripts/00-bootstrap-state.sh has been run once
#   - Azure CLI logged in with Contributor role
#
# Usage:
#   ./scripts/01-apply.sh

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status()  { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error()   { echo -e "${RED}[ERROR]${NC} $1"; }
print_section() { echo; echo -e "${GREEN}========================================${NC}"; echo -e "${GREEN}$1${NC}"; echo -e "${GREEN}========================================${NC}"; echo; }

# ─── Environment check ────────────────────────────────────────────────────────
if [[ ! -f /.dockerenv ]] || [[ ! -d /mnt/urbalurbadisk ]]; then
    print_error "This script must run inside the provision-host container"
    exit 1
fi

# ─── Load config ──────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLATFORM_DIR="$SCRIPT_DIR/.."
TOFU_DIR="$PLATFORM_DIR/tofu"
CONFIG_FILE="$PLATFORM_DIR/azure-aks-config.sh"

if [[ ! -f "$CONFIG_FILE" ]]; then
    print_error "Config not found: $CONFIG_FILE"
    echo "  cp platforms/aks/azure-aks-config.sh-template platforms/aks/azure-aks-config.sh"
    exit 1
fi

source "$CONFIG_FILE"

print_section "AKS PLATFORM — OPENTOFU APPLY"

# ─── Azure login ──────────────────────────────────────────────────────────────
print_status "Checking Azure login..."
if ! az account show >/dev/null 2>&1; then
    az login --tenant "$TENANT_ID" --use-device-code
fi
az account set --subscription "$SUBSCRIPTION_ID"
print_success "Using subscription: $(az account show --query name -o tsv)"

# ─── PIM check ────────────────────────────────────────────────────────────────
print_status "Checking Contributor role..."
if ! az role assignment list \
    --scope "/subscriptions/$SUBSCRIPTION_ID" \
    --query "[?roleDefinitionName=='Contributor' && principalType=='User']" \
    -o tsv 2>/dev/null | grep -q .; then
    print_warning "Contributor role not active"
    echo "  Activate at: https://portal.azure.com/?feature.msaljs=true#view/Microsoft_Azure_PIMCommon/ActivationMenuBlade/~/azurerbac"
    read -p "  Press Enter after activating..."
fi
print_success "Contributor role active"

# ─── Get storage account key for backend ──────────────────────────────────────
print_status "Fetching state storage account key..."
export ARM_ACCESS_KEY=$(az storage account keys list \
    --resource-group "$STATE_RESOURCE_GROUP" \
    --account-name "$STATE_STORAGE_ACCOUNT" \
    --query "[0].value" -o tsv)

if [[ -z "$ARM_ACCESS_KEY" ]]; then
    print_error "Could not fetch storage account key"
    echo "  Has 00-bootstrap-state.sh been run?"
    exit 1
fi
print_success "Storage account key loaded (not logged)"

# ─── Generate tfvars ──────────────────────────────────────────────────────────
TFVARS_FILE="$TOFU_DIR/terraform.tfvars"
print_status "Generating terraform.tfvars from config..."

cat > "$TFVARS_FILE" <<EOF
# Auto-generated by 01-apply.sh from azure-aks-config.sh — do not edit manually
tenant_id       = "$TENANT_ID"
subscription_id = "$SUBSCRIPTION_ID"

resource_group  = "$RESOURCE_GROUP"
cluster_name    = "$CLUSTER_NAME"
location        = "$LOCATION"

node_count      = $NODE_COUNT
node_size       = "$NODE_SIZE"
min_count       = $MIN_COUNT
max_count       = $MAX_COUNT
os_disk_size_gb = $OS_DISK_SIZE

tag_cost_center    = "$TAG_COST_CENTER"
tag_project        = "$TAG_PROJECT"
tag_environment    = "$TAG_ENVIRONMENT"
tag_business_owner = "$TAG_BUSINESS_OWNER"
tag_it_owner       = "$TAG_IT_OWNER"
EOF

print_success "terraform.tfvars generated"

# ─── tofu init ────────────────────────────────────────────────────────────────
print_section "Step 1: tofu init"
cd "$TOFU_DIR"

tofu init \
    -backend-config="resource_group_name=$STATE_RESOURCE_GROUP" \
    -backend-config="storage_account_name=$STATE_STORAGE_ACCOUNT" \
    -backend-config="container_name=$STATE_CONTAINER" \
    -backend-config="key=$STATE_KEY" \
    -reconfigure

print_success "tofu init complete"

# ─── tofu plan ────────────────────────────────────────────────────────────────
print_section "Step 2: tofu plan"
tofu plan -out=tfplan
print_success "Plan saved to tfplan"

echo
read -p "Review the plan above. Apply? (y/N): " confirm
[[ "${confirm,,}" != "y" ]] && { print_warning "Aborted — no changes made"; exit 0; }

# ─── tofu apply ───────────────────────────────────────────────────────────────
print_section "Step 3: tofu apply"
print_status "This will take 5-10 minutes..."
tofu apply tfplan

print_success "tofu apply complete"

# ─── Write kubeconfig ─────────────────────────────────────────────────────────
print_section "Step 4: Save kubeconfig"
mkdir -p "$(dirname "$KUBECONFIG_FILE")"

tofu output -raw kube_config_raw > "$KUBECONFIG_FILE"
chmod 600 "$KUBECONFIG_FILE"
print_success "Kubeconfig written to: $KUBECONFIG_FILE"

# ─── Quick validation ─────────────────────────────────────────────────────────
print_section "Step 5: Validate"
export KUBECONFIG="$KUBECONFIG_FILE"

if kubectl get nodes >/dev/null 2>&1; then
    print_success "Cluster is accessible"
    echo
    kubectl get nodes
else
    print_error "Cannot reach cluster — check kubeconfig"
    exit 1
fi

# ─── Summary ──────────────────────────────────────────────────────────────────
print_section "APPLY COMPLETE"
echo "Cluster:      $CLUSTER_NAME"
echo "Location:     $LOCATION"
echo "Kubeconfig:   $KUBECONFIG_FILE"
echo
echo "Next step:"
echo "  ./platforms/aks/scripts/02-post-apply.sh"
