#!/bin/bash
# Generated by debug-litellm.sh on Fri Mar 28 13:44:54 CET 2025
# Run this script to fix issues identified with your LiteLLM deployment

echo 'Fixing master key mismatch...'
# Fix the LiteLLM master key in the ConfigMap to match the secret
CONFIG_PATCH="{\"data\":{\"config.yaml\":\"\"}}"
kubectl patch configmap litellm-config -n default --type=merge -p "$CONFIG_PATCH"
echo 'ConfigMap patched with correct master key'

# Restart the LiteLLM pod to apply changes
kubectl rollout restart deployment -n default $(kubectl get deployment -n default | grep litellm | awk '{print $1}')
echo 'LiteLLM pod restarted'
